#!/usr/bin/bash
conf=${1-"debug"}
./premake5 gmake2
if [ "$1" == "clean" ]; then
make clean
exit 0
fi
if [ "$1" == "gdb" ]; then
conf="debug"
fi
make config=$conf || exit

if [ "$1" == "gdb" ]; then
    gdb ./bin/Sandbox
    exit
fi

./bin/Sandbox
